image: hugomods/hugo:ext-alpine  # Use a more specific version if needed

variables:
  HUGO_ENV: production
  THEME_URL: "github.com/gdr-sdl/theme"

default:
  before_script:
    - hugo version
    - git config --global --add safe.directory /builds/gdr-scilog/site  # Fix potential git safety issues
    - hugo mod get -u $THEME_URL
    - hugo mod tidy
    - hugo mod vendor

# Use everywhere except on the default branch
test:
  script:
    - hugo --minify
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

# Run only on the default branch
create-pages:
  stage: deploy
  script:
    - hugo --minify --config hugo.toml
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH